#!/bin/sh

# Convert vmdk to a deployable dmg

set -e

cleanup ()
{
    rv=$?
    [ -n "$device" ] && hdiutil detach "$device"
    exit $rv
}

trap cleanup INT TERM EXIT

vmdk_path=$1
dmg_path=${2:-image.dmg}

if [ $# -lt 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ];
then
    echo "Usage: vmdk2dmg vmname|vmdk_file [/path/to/dmg]"
    exit 0
fi

if [ "${1%.vmdk}" = "$1" ];
then
    vmdk_path=$(VBoxManage showvminfo "$1" --machinereadable \
        | sed  -n 's/".*"="\(.*vmdk\)"/\1/p')
fi

if [ ! -f "$vmdk_path" ];
then
    echo "error: $vmdk_path is invalid path"
    exit 1
fi

device=$(vdmutil attach "$vmdk_path" | head -n 1)

echo "==> Mount as $device"
echo "==> Converting to $dmg_path"
hdiutil create -srcdevice "$device" -format UDZO "$dmg_path"
