#!/bin/sh

# Convert vmdk to a deployable dmg

set -e

cleanup ()
{
    [ -n "$device" ] && hdiutil detach "$device"
}

trap cleanup EXIT

vmdk_path=$1
dmg_path=${2:-image.dmg}

if [ $# -lt 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ];
then
    echo "Usage: vmdk2dmg /path/to/vmdk [/path/to/dmg]"
    exit 0
fi

if [ ! -f "$vmdk_path" ];
then
    echo "error: $vmdk_path is invalid"
    exit 1
fi

device=$(vdmutil attach "$vmdk_path" | head -n 1)

echo "==> Mount as $device"
echo "==> Converting to $dmg_path"
hdiutil create -srcdevice "$device" -format UDZO "$dmg_path"
